FROM debian:wheezy

#Default branch name develop
ARG BRANCH_NAME=develop
#Default
ARG REPO_SLUG=vortex/vortex
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo

#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY vortex.tar.gz /vortex.tar.gz
RUN tar -xvf /vortex.tar.gz

#ADD . /vortex
RUN cd /vortex/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /vortex && scripts/windows-crosscompile/compile-vortex.sh
